In [1]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [15]:
from sklearn.cluster import KMeans
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [16]:
first = pd.read_csv('gdrive/MyDrive/kmean.csv')

In [17]:
model = KMeans(n_clusters=3, init=np.array([[8.5, 8.75], [10.5, 7.13], [12.0, 5.0]]), max_iter=100, n_init=1)

In [18]:
first

Object   X   Y  Cluster
0        1   2  13        0
1        2   5   6        1
2        3  17   7        2
3        4   5  10        1
4        5  12   6        2
5        6  18   4        0
6        7  17   1        1
7        8   3  14        0
8        9  13   4        1
9       10  12  10        1
10      11  10   6        1
11      12   7   2        2
12      13  11   4        0
13      14  13  17        1
14      15   9   3        1

In [19]:
X =first[['X','Y']]


In [20]:
model = model.fit(X)

In [21]:
test =model.labels_

In [22]:
model.get_params()

{'algorithm': 'lloyd',
 'copy_x': True,
 'init': array([[ 8.5 ,  8.75],
        [10.5 ,  7.13],
        [12.  ,  5.  ]]),
 'max_iter': 100,
 'n_clusters': 3,
 'n_init': 1,
 'random_state': None,
 'tol': 0.0001,
 'verbose': 0}

In [23]:
model.score(X)

-293.10476190476186

In [24]:
data = []
for i in range(len(test)):
  if(test[i]== 0 ):
    data.append(X.loc[i].to_numpy())

In [25]:
data = list(X.to_numpy())


In [26]:
model.score(data)

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


-293.10476190476186

In [35]:
model.inertia_

293.10476190476186

In [28]:
c = model.cluster_centers_

In [29]:
data

[array([ 2, 13]),
 array([5, 6]),
 array([17,  7]),
 array([ 5, 10]),
 array([12,  6]),
 array([18,  4]),
 array([17,  1]),
 array([ 3, 14]),
 array([13,  4]),
 array([12, 10]),
 array([10,  6]),
 array([7, 2]),
 array([11,  4]),
 array([13, 17]),
 array([9, 3])]

In [30]:
from math import sqrt
sum = 0
for i in data:
  sum+=sqrt((i[0]-c[0][0])**2+(i[1]-c[0][1])**2)

In [31]:
sum

130.2984088984534

In [36]:
first['Cluster'] = model.labels_

In [37]:
first

Object   X   Y  Cluster
0        1   2  13        0
1        2   5   6        0
2        3  17   7        2
3        4   5  10        0
4        5  12   6        1
5        6  18   4        2
6        7  17   1        2
7        8   3  14        0
8        9  13   4        2
9       10  12  10        1
10      11  10   6        1
11      12   7   2        2
12      13  11   4        2
13      14  13  17        0
14      15   9   3        2

In [40]:
c

array([[ 5.6       , 12.        ],
       [11.33333333,  7.33333333],
       [13.14285714,  3.57142857]])

In [44]:
ch = first[first['Cluster'] == 0]

In [45]:
ch

Object   X   Y  Cluster
0        1   2  13        0
1        2   5   6        0
3        4   5  10        0
7        8   3  14        0
13      14  13  17        0

In [47]:
n_arr = ch[['X','Y']].to_numpy()
n_arr

array([[ 2, 13],
       [ 5,  6],
       [ 5, 10],
       [ 3, 14],
       [13, 17]])

In [48]:
sum = 0
for i in n_arr:
  sum+=sqrt((i[0]-c[0][0])**2+(i[1]-c[0][1])**2)

In [49]:
sum/len(n_arr)

4.813076866197262