In [1]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [ ]:
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

In [ ]:
train = pd.read_csv('gdrive/MyDrive/candy-data.csv')
test = pd.read_csv('gdrive/MyDrive/candy-test.csv')

In [ ]:
train

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0               100 Grand          1       0        1               0       0   
1            3 Musketeers          1       0        0               0       1   
2                One dime          0       0        0               0       0   
3             One quarter          0       0        0               0       0   
4               Air Heads          0       1        0               0       0   
..                    ...        ...     ...      ...             ...     ...   
65       Snickers Crisper          1       0        1               1       0   
66        Sour Patch Kids          0       1        0               0       0   
67  Sour Patch Tricksters          0       1        0               0       0   
68              Starburst          0       1        0               0       0   
69    Strawberry bon bons          0       1        0               0       0   

    crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                  1     0    1         0         0.732         0.860   
1                  0     0    1         0         0.604         0.511   
2                  0     0    0         0         0.011         0.116   
3                  0     0    0         0         0.011         0.511   
4                  0     0    0         0         0.906         0.511   
..               ...   ...  ...       ...           ...           ...   
65                 1     0    1         0         0.604         0.651   
66                 0     0    0         1         0.069         0.116   
67                 0     0    0         1         0.069         0.116   
68                 0     0    0         1         0.151         0.220   
69                 0     1    0         1         0.569         0.058   

    winpercent  Y  
0    66.971725  1  
1    67.602936  1  
2    32.261086  0  
3    46.116505  0  
4    52.341465  1  
..         ... ..  
65   59.529251  1  
66   59.863998  1  
67   52.825947  1  
68   67.037628  1  
69   34.578991  0  

[70 rows x 14 columns]

In [ ]:
train_=train

In [ ]:
train = train_[(train['competitorname']!='Candy Corn') & (train['competitorname']!='Reeses stuffed with pieces') & (train['competitorname']!='Nerds')]

In [ ]:
x_train = train[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]

In [ ]:
y_train =train['Y']

In [ ]:
model =LogisticRegression(random_state = 2019, solver = 'lbfgs').fit(x_train, y_train)

In [ ]:
confusion_matrix(y_train,model.predict(x_train))

array([[27,  5],
       [ 9, 26]])

In [ ]:
threshold = 0.5
y_pred = (model.predict_proba(x_train)[:, 1] > threshold).astype('float')
confusion_matrix(y_train, y_pred)


array([[27,  5],
       [ 9, 26]])

In [ ]:
x_test = test[['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent', 'pricepercent']]
y_test =test['Y']

In [ ]:
threshold = 0.5
y_pred = (model.predict_proba(x_test)[:, 1] > threshold).astype('float')
confusion_matrix(y_test, y_pred)

array([[8, 2],
       [2, 3]])

In [ ]:
confusion_matrix(y_test,model.predict(x_test))

array([[8, 2],
       [2, 3]])

In [ ]:
from sklearn.metrics import recall_score
from sklearn.metrics import auc
from sklearn.metrics import precision_score
from sklearn import metrics

In [ ]:

fpr, tpr, thresholds = metrics.roc_curve(y_test, model.predict(x_test))
# metrics.auc(fpr, tpr)
fpr

array([0. , 0.2, 1. ])

In [ ]:
# model.predict(x_test) == y_pred
recall_score(y_test,model.predict(x_test))

0.6

In [ ]:
precision_score(y_test,model.predict(x_test))

0.6

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(model.predict(x_test),y_test)

0.7000000000000002

In [ ]:
y_score = model.predict_proba(x_test)[:, 1]

auc = roc_auc_score(y_test, y_score > 0.5)

In [ ]:
auc

0.3

In [ ]:
from sklearn import metrics
from sklearn.metrics._plot.roc_curve import auc
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
Y1 = y_test
Y2 = model.predict(x_test)
p = model.predict_proba(x_test)
fpr, tpr, threshold = metrics.roc_curve(Y1, p[:,1])
AUC=metrics.auc(fpr, tpr)
print("AUC ",np.round(AUC,3))

# len(p) == len(Y2)

AUC  0.88


In [ ]:
threshold

array([1.782184  , 0.782184  , 0.73210344, 0.48637713, 0.36934103,
       0.10914146])

In [ ]:
AUC=metrics.auc(fpr[:3], tpr[:3])
print("AUC ",np.round(AUC,3))


AUC  0.0
