In [2]:
import tensorflow as tf

In [3]:
tf.random.set_seed(2)

In [6]:
shape = (2, 2,2)

tensor = tf.constant(tf.random.normal(shape))

In [7]:
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 4.3616885e-01, -1.9093795e+00],
        [ 1.3789066e+00, -1.0405852e+00]],

       [[-9.5584162e-04,  1.6947803e-01],
        [ 9.1563100e-01,  5.5124867e-01]]], dtype=float32)>

In [8]:
tensor[0][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=-1.0405852>